# imprting NumpP

In [1]:
import numpy as np

NumPy陣列是我們在課程中將使用NumPy的主要方式。NumPy陣列基本上有兩種類型：向量和矩陣。向量是嚴格的一維（1D）陣列，而矩陣是二維的（但你應該注意，矩陣仍然可以只有一行或一列）。
## 為什麼使用Numpy陣列？為什麼不只是使用列表？
使用Numpy陣列而不是“標準”Python列表對我們來說有很多原因。我們的主要原因包括：
* Numpy陣列的內存效率比列表高
* 能夠輕鬆擴展到N維對象
* Numpy陣列的計算速度快
* 使用Numpy進行廣播操作和函數
* 我們使用的所有數據科學和機器學習庫都是使用Numpy構建的
## Numpy陣列可以做什麼的簡單示例
這是使用Numpy陣列的一個簡單示例，它可以做到什麼程度。


支持GPU

https://blog.csdn.net/sinat_29957455/article/details/107072991
nvidia cuda numpy

In [3]:
my_list=[1,2,3]
my_array = np.array(my_list)
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


## arange

In [5]:
v1=np.arange(10)
print(v1)
v2=np.arange(1,6)
print(v2)
v3=np.arange(1,10,2)
print(v3)
v4=np.arange(10,-2,-2)
print(v4)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[1 3 5 7 9]
[10  8  6  4  2  0]


## linspace

In [9]:
v1=np.linspace(1,10,100)
print(type(v1))
print(v1)

<class 'numpy.ndarray'>
[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.363

# Random

Numpy也有許多方法來創建隨機數陣列:

In [13]:
print(np.random.random(3))
print("=================")
print(np.random.rand(5,5))
print("====================")
v1=np.random.rand(3,2)
print(np.random.rand(3,2))
print(v1.mean())
print(v1.std())

[0.99017194 0.53017815 0.09949398]
[[0.91353396 0.67328367 0.3392019  0.41260643 0.13978314]
 [0.5679526  0.35584423 0.23852594 0.94708655 0.40502871]
 [0.11520281 0.41998714 0.99934431 0.51218424 0.13992872]
 [0.07158715 0.64996229 0.17412334 0.38432106 0.33989761]
 [0.73314697 0.80118387 0.20700588 0.58745546 0.69019788]]
[[0.00307555 0.69532209]
 [0.3002462  0.22516066]
 [0.95143429 0.58811498]]
0.7148740299842888
0.26530995568593996


### randn
標準正態分佈是一種特殊的常態分佈，其平均數（μ）為0，標準差（σ）為1。在標準正態分佈中，數據點主要集中在平均值附近，並且隨著距離平均值的增加而呈指數下降。這種分佈的曲線形狀呈鐘形，並且在平均值附近有一個尖峰。
在機器學習和統計學中，標準正態分佈通常用於建模和分析，並且在許多算法和技術中被廣泛應用。

In [11]:
np.random.randn(2)

array([-0.04377959, -0.24044461])

In [15]:
v1= np.random.randn(5,5)

print(v1.mean())
print(v1.std())

0.20428456061913255
0.9472677067670683


### randint

從`low`（包含）到`high`（不包含）return隨機整數。

In [18]:
v1=np.random.randint(1,100)
print(v1)
v2=np.random.randint(1,100,10)
print(v2)

66
[19 10 53 66 88 92 82 29 63 27]


In [20]:
v3=np.random.choice(range(1,100),10,replace=False)
print(v3)

[51 56 13 38 55 14 43 98 35 45]


In [22]:
#replace=False 不會抽重複
myData=range(1,100)
v3=np.random.choice(myData,2,replace=False)
print(v3)

[51 71]


In [25]:
#洗牌shuffle
arr=np.arange(1,100)
print(arr)
np.random.shuffle(arr)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[88 31 71 91 84 82 47 69 80 61 95 11 36 60 28 58 50 56 65 96 53 92 98 32
 67 63 83 35 59 41 85 30 10 48  4 16 46 22 25 89 20 52  8  6 19 57 18 74
 17 78 77 66 40  1 23 55  7 75 34 14 97 37 51 87 42 33  5 15 70 86 68 72
 99 27 94 76 24 12 38 39 62 45 49 64 43 79 26  3 81 21 90  2 73 29 54 13
 44 93  9]


## seed

可以用來設置隨機狀態，以便可以重現相同的"隨機"結果

In [26]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
#洗牌
np.random.seed(42)
arr=np.arange(1,100)
print(arr)
np.random.shuffle(arr)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[63 41 96 19 98 85 65 43 11  1 32 77 48 27 45  5 23 13 89 74 50 71 69 16
 40 34 10 82 12 66 95 31 29 90  6 46 70 36 17 73 35  8 56 28 20 81 26 54
 14 25  4 18 39  9 78  7 80 37 92 57 99 55 44 51 67 47 68 62 97 79 42 59
 49 86 58 76 33 94 60 64 84 38 30  2 53 22  3 24 88 91 75 87 83 21 61 72
 15 93 52]


## 陣列屬性和方法

討論一些陣列的有用屬性和方法:

In [36]:
arr1=np.arange(25)
print(arr1)
print(arr1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


## Reshape
return一個包含相同數據但具有新形狀的陣列。

In [37]:
arr2=arr.reshape(5,5)

print(arr2)
print(arr2.shape)
print("=================")
arr2[0][0]=100
print(arr)

print("==================")
print(id(arr2))
print(id(arr1))

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]
(5, 5)
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]
1126258981552
1126261590800


In [38]:
data = [1,2,3,4,5]
class MyData1:
    def add(v):
        data.append(v)
class MyData2:
    def add(v):
        data.append(v)
myData1 = MyData1  
myData2 = MyData2

In [40]:
arr1=np.arange(25)
print(arr1)
print(arr1.shape)
arr2=np.resize(arr1,(5,5))
print(arr2)
arr2[0][0]=100
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


### max,min,argmax,argmin

In [43]:
np.random.seed(60)
v2=np.random.randint(1,100,10)
print(v2)
print(v2.max())
print(v2.min())
print(v2.argmax())#找出數值最大值的index
print(v2.argmin())#找出數值最小值的index

[78 66 71 11 16 73 18 35 34 88]
88
11
9
3


In [48]:
arr=np.array([1.2,3.4,5.6])
print(arr)
print(arr.dtype)
arr2=arr.astype(np.float16)
print(arr2)
print(arr.dtype)
arr3=arr.astype(np.int8)
print(arr3)
print(arr3.dtype)

arr4=np.array([2147483648,3147483648,4147483648])
print(arr4)
print(arr.dtype)
arr5=arr4.astype(np.int32)
print(arr5)
print(arr5.dtype)

[1.2 3.4 5.6]
float64
[1.2 3.4 5.6]
float64
[1 3 5]
int8
[2147483648 3147483648 4147483648]
float64
[-2147483648 -1147483648  -147483648]
int32


## 區間取值

In [51]:
arr= np.arange(0,11)
print(arr)
print(arr[8])
print(arr[1:6])
print(arr[3:])
print(arr[-5:-2])
print(arr[:-2])
print(arr[:-3])

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[1 2 3 4 5]
[ 3  4  5  6  7  8  9 10]
[6 7 8]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7]


In [54]:
arr=np.arange(0,11)
print(arr)
arr[0:5]=100
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100   5   6   7   8   9  10]


In [56]:
arr=np.arange(0,11)
arr[0::2]=10#對所有偶數的index內容改為10
print(arr)

[10  1 10  3 10  5 10  7 10  9 10]


In [61]:
#List
py_list=list(range(10))
print(py_list)
py_list[0:5]=[10]*5
print(py_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 10, 10, 10, 10, 5, 6, 7, 8, 9]


In [62]:
py_list=list(range(10))
print(py_list)
py_list2=py_list[0:5]
print(py_list2)
py_list2[2]=100
print(py_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [66]:
arr=np.arange(0,11)
print(arr)
arr2=arr[0:6]
print(arr2)
arr2[:]=100
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5]
[100 100 100 100 100 100   6   7   8   9  10]


In [76]:
arr=np.arange(1,11)
print(arr>4)
newArry=arr[arr>4]
print(newArry)

x=2
newArry2=arr[arr>x]
print(newArry2)

[False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10]


## NumPy運算

In [73]:
arr1=np.arange(0,10)
arr2=np.arange(10,20)
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [74]:
arr1+arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [78]:
print(arr1*5)
print(arr1+2)

[ 0  5 10 15 20 25 30 35 40 45]
[ 2  3  4  5  6  7  8  9 10 11]


In [79]:
arr1=np.arange(0,10)
print(arr1)
print(arr1/arr1)

[0 1 2 3 4 5 6 7 8 9]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\student\AppData\Local\Temp\ipykernel_4608\1318468881.py:3: RuntimeWarning: invalid value encountered in divide
  print(arr1/arr1)


In [81]:
arr1=np.arange(0,5)
print(1/arr1)

[       inf 1.         0.5        0.33333333 0.25      ]


C:\Users\student\AppData\Local\Temp\ipykernel_4608\403282929.py:2: RuntimeWarning: divide by zero encountered in divide
  print(1/arr1)


In [93]:
arr1=np.arange(0,8)
print(1/arr1)#在 NumPy 中，當運算結果超出數值的極限，導致無窮大(infinity)的情況時
newArry=1/arr1
print(arr1[newArry!=np.inf])
print(newArry==np.inf)
result=arr1/np.finfo(float).tiny
print(arr1)
print(result)
print(np.finfo(float).tiny)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714]
[1 2 3 4 5 6 7]
[ True False False False False False False False]
[0 1 2 3 4 5 6 7]
[0.00000000e+000 4.49423284e+307 8.98846567e+307 1.34826985e+308
             inf             inf             inf             inf]
2.2250738585072014e-308


C:\Users\student\AppData\Local\Temp\ipykernel_4608\1111494039.py:2: RuntimeWarning: divide by zero encountered in divide
  print(1/arr1)#在 NumPy 中，當運算結果超出數值的極限，導致無窮大(infinity)的情況時
C:\Users\student\AppData\Local\Temp\ipykernel_4608\1111494039.py:3: RuntimeWarning: divide by zero encountered in divide
  newArry=1/arr1
C:\Users\student\AppData\Local\Temp\ipykernel_4608\1111494039.py:6: RuntimeWarning: overflow encountered in divide
  result=arr1/np.finfo(float).tiny


In [90]:
arr1=np.arange(0,10)
print(arr1)
print(np.exp(arr1))#e的指數
print(np.exp(-arr1))

[0 1 2 3 4 5 6 7 8 9]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[1.00000000e+00 3.67879441e-01 1.35335283e-01 4.97870684e-02
 1.83156389e-02 6.73794700e-03 2.47875218e-03 9.11881966e-04
 3.35462628e-04 1.23409804e-04]


#### 在NumPy中使用np.log(arr)的意思是對arr這個陣列中的每個元素進行自然對數運算。這個函數計算的是以e(約等於271828)為底的對數。

In [94]:
print(arr)
np.log(arr)

[ 1  2  3  4  5  6  7  8  9 10]


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [97]:
a1=np.array([1e308*10])
print(a1)
a2=np.array([1e308*1.5e308,1.5e305])
print(a2*2)

[inf]
[    inf 3.e+305]


## 軸邏輯
在處理二維陣列（矩陣）時，我們必須考慮行和列。當我們進入到 pandas 的相關部分時，這會變得非常重要。在陣列中，軸 0（零）代表垂直軸（行），而軸 1 則是水平軸（列）。這些值（0,1）對應於 `arr.shape` 返回值的順序。
讓我們看看這如何影響我們上面提到的摘要統計計算：
- 當使用軸 0 進行操作時，意味著沿著行（垂直方向）進行計算，將每一列的值聚合起來。例如，計算每一列的總和或平均值。
- 當使用軸 1 進行操作時，則沿著列（水平方向）進行計算，將每一行的值聚合起來。例如，計算每一行的總和或平均值。
這種區分在進行統計分析時非常重要，它確保你可以按照期望的方向對數據進行操作。這種對軸的理解同樣適用於更高維度的數據處理。讓我們看一個例子，如果有一個矩陣 `arr` 如下所示：
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```
- 使用 `np.sum(arr, axis=0)` 將返回每一列的總和：`[12, 15, 18]`
- 使用 `np.sum(arr, axis=1)` 將返回每一行的總和：`[6, 15, 24]`
這樣的操作讓我們可以根據具體需求選擇適當的軸進行數據統計。

In [98]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
arr_2d.sum()

78

In [100]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [101]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [104]:
arr1=np.array([10**-324.5])
print(arr1)

[0.]
