In [1]:
import numpy as np

# 創建一個包含10個零的陣列

In [2]:
v1=np.arange(10)
print(v1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 創建一個包含10個1的陣列

In [7]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# 創建一個包含10個5的陣列

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 創建一個包含10到50的陣列


In [11]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# 要創建一個包含10個50的所有偶數整數的陣列


In [12]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# 要創建一個3x3矩陣，其中包含0到8的值


In [13]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# NumPy生成一個包含25個從標準正態分布的亂數

In [15]:
print(np.random.random(25))

[0.99153111 0.99645331 0.60063463 0.91445703 0.70723964 0.86304644
 0.37045109 0.05141393 0.88812765 0.73941218 0.76651093 0.46217676
 0.80378552 0.67081515 0.27491365 0.58634587 0.59101658 0.21139497
 0.18921079 0.18769032 0.04373141 0.3615742  0.50915382 0.81722387
 0.2658263 ]
